### ISSUE TITLE
Bug with Proxy Handling

### ISSUE THREAD

**Issue by ebollens** [ucla/casa-on-rails#50]
Right now, when we're running CASA on Rails multiple time on the same host, and using Nginx to route properly, we're hitting the following error when trying to access `/casa/out/payloads`:

```
F, [2015-04-06T16:20:45.332355 #9188] FATAL -- : 
IPAddr::InvalidAddressError (invalid address):
  app/controllers/casa/out_controller.rb:15:in `new'
  app/controllers/casa/out_controller.rb:15:in `block (2 levels) in <class:OutController>'
  app/controllers/casa/out_controller.rb:13:in `each'
  app/controllers/casa/out_controller.rb:13:in `block in <class:OutController>'
```

This has to do with Nginx mangling the requestor address as it passes through the reverse proxy.

**Comment by ebollens** [comment]
@rrocchio this is why UCLA's CASA can't currently query UCSD's CASA.
